#!/bin/sh

echo "--- Go to SVN branch ---"
cd $SVN_PATH"mobile/"

echo "--- Revert SVN ---"
svn revert --recursive .

echo "--- Update SVN ---"
svn update

echo "--- Delete SVN Mobile Assets ---"
svn rm $SVN_PATH"mobile/assets"
svn commit . -m "delete mobile assets"

echo "--- Move to mobile-pre-sales ---"
cd $PRESALE_PATH

echo "--- Copying files ---"
cp -avR $PRESALE_PATH"build/public/" $SVN_PATH

echo "--- Add untracked files to SVN ---"
cd $SVN_PATH
svn st | grep '^\?' | sed 's/^\? *//' | xargs -I% svn add %

echo "--- Remove locally deleted files from SVN ---"
svn st | grep ! | cut -d! -f2| sed 's/^ *//' | sed 's/^/"/g' | sed 's/$/"/g' | xargs svn rm

echo "--- Commiting SVN ---"
svn commit -m " update /mobile to svn"

echo "--- Yorklab deploy completed --"
